name: cicd_full_devops

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: hieuduong1/myapp

jobs:
  # ================= CI =================
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/


      - name: Snyk Scan
        run: npx snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # ================= DOCKER =================
  docker:
    runs-on: ubuntu-latest
    needs: build

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate tag
        id: meta
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}


      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest


      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
          exit-code: 1
          severity: CRITICAL
          scanners: vuln

  # ================= CD - STAGING =================
  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker

    environment:
      name: staging

    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            set -e
            export KUBECONFIG=~/.kube/config
            export IMAGE_TAG=${{ needs.docker.outputs.image_tag }}

            echo "Deploying to STAGING: $IMAGE_TAG"

            envsubst '$IMAGE_TAG' < /home/ubuntu/app.yaml | kubectl apply -f -

            kubectl rollout status deployment/midterm-web-deployment -n default

  # ================= CD - PRODUCTION =================
  deploy-production:
    runs-on: ubuntu-latest
    needs: docker

    environment:
      name: production
      url: https://devoops.shop

    steps:
      - name: Deploy to Production with rollback
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            set -e
            export KUBECONFIG=~/.kube/config
            export IMAGE_TAG=${{ needs.docker.outputs.image_tag }}

            echo "Deploying to PRODUCTION: $IMAGE_TAG"

            envsubst '$IMAGE_TAG' < /home/ubuntu/app.yaml | kubectl apply -f -

            kubectl rollout status deployment/midterm-web-deployment -n default || \
            (echo "Rollback..." && kubectl rollout undo deployment/midterm-web-deployment)

             # 3. HEALTH CHECK 
            echo "Starting Health Check..."
            APP_URL="https://devoops.shop"
            MAX_RETRIES=5
            INTERVAL=10
            
            for i in $(seq 1 $MAX_RETRIES); do
              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $APP_URL || echo "000")
              
              if [ "$HTTP_CODE" -eq 200 ]; then
                echo " Health check passed (HTTP 200)!"
                exit 0
              fi
              
              echo "Attempt $i: App returned $HTTP_CODE. Retrying in ${INTERVAL}s..."
              sleep $INTERVAL
            done

            echo "Health check failed after $MAX_RETRIES attempts!"
            echo "Initiating Rollback..."
            kubectl rollout undo deployment/midterm-web-deployment
            exit 1
